### ISSUE TITLE
WildFly 10 CR1 deploy doesn't work

### ISSUE THREAD

**Issue by fiorenzino** [undertow-io/undertow.js-examples#1]
Hi, 

i tried to deploy the angular example on WildFly 10 CR1 and i have this error, calling the angular method register():

Members.save($scope.newMember, function(data) {
            // mark success on the registration form
            $scope.successMessages = [ 'Member Registered' ];
            // Update the list of members
            $scope.refresh();
            // Clear the form
            $scope.reset();
        }, function(result) {
            if ((result.status == 409) || (result.status == 400)) {
                $scope.errors = result.data;
            } else {
                $scope.errorMessages = [ 'Unknown  server error' ];
            }
            $scope.$apply();
        });

i have this error on wildfly log:

4:43:21,240 ERROR [io.undertow.request](default task-1) Undertow request failed HttpServerExchange{ POST /wildfly-kitchensink-utjs-angularjs/rest/members request {Accept=[application/json, text/plain, _/_], X-Requested-With=[XMLHttpRequest], Accept-Language=[it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2,fr;q=0.2], Accept-Encoding=[gzip, deflate], Origin=[http://localhost:8080], User-Agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36], Connection=[keep-alive], Content-Length=[83], Content-Type=[application/json;charset=UTF-8], Referer=[http://localhost:8080/wildfly-kitchensink-utjs-angularjs/], Host=[localhost:8080]} response {X-Powered-By=[Undertow/1], Server=[WildFly/10]}}: java.lang.NoSuchMethodError: io.undertow.util.StringReadChannelListener.<init>(Lorg/xnio/Pool;)V
    at io.undertow.js.StringReadHandler$1$1.<init>(StringReadHandler.java:54)
    at io.undertow.js.StringReadHandler$1.run(StringReadHandler.java:54)
    at io.undertow.util.SameThreadExecutor.execute(SameThreadExecutor.java:35)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:784)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

I used:
WildFly 10 CR1, jdk1.8.0_60.jdk.

it seems that the the StringReadChannelListener constructor method not exists in the version deployed on wildfly.

Best Regards

Fiorenzo

**Comment by justinlinz** [comment]
I received the same error with WildFly 10 CR4.  I updated the undertow-core module in:
modules\system\layers\base\io\undertow\core\main as well as the corresponding module.xml version with the latest undertow core library:
http://repository.jboss.org/nexus/content/groups/public/io/undertow/undertow-core/1.3.9.Final/

This appears to be the same version referenced by the wildfly 10 cr4 pom (its corresponding wildfly core pom actually), but for some reason the compiled version of wildfly 10 cr4 i downloaded had undertow-core 1.3.3.  I suspect if I would have built wildfly from source this error would not have occurred.
